### ISSUE TITLE
some error can't run bot.py

### ISSUE THREAD

**Issue by speccycy** [timraay/Archon#30]
Python 3.8.18

```
PS C:\PostScriptum Bot\Archon> python.exe .\bot.py
Traceback (most recent call last):
  File ".\bot.py", line 151, in <module>
    logging.basicConfig(format='[%(asctime)s][%(levelname)s] %(message)s', datefmt='%m/%d %H:%M:%S', filename=logname, filemode='w+', level=logging.INFO)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1988, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
```

**Comment by jneil1992** [comment]
Is that the whole traceback?

**Comment by speccycy** [comment]
> Is that the whole traceback?

yes

**Comment by timraay** [comment]
> > Is that the whole traceback?
> 
> yes

No it is not. While this does say where the error originates from, it never mentions what the actual error is, which should come right after. And without that information, all this really tells us is that the logging module _for some reason_ couldn't open a file.

If you include the line(s) that follow we should be able to tell you what exactly you should be looking for, but if I were to have a guess, it would say the following;
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\PostScriptum Bot\Archon\logs\Archon-123blabla.log'
```
...which happens because by default, no `logs` folder exists within the repo as I just noticed, which will need to be manually created.

**Comment by speccycy** [comment]
Thank you for your help.
I solved this problem.

It is necessary to create a logs folder in order to run the bot.
